sudo: required
services:
  - docker
before_install:
  - docker build -t pkaranthaker/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true pkaranthaker/react-test npm test
after_success:
  - docker build -t pkaranthaker/multi-client ./client
  - docker build -t pkaranthaker/multi-nginx  ./nginx
  - docker build -t pkaranthaker/multi-server ./server
  - docker build -t pkaranthaker/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push pkaranthaker/multi-client
  - docker push pkaranthaker/multi-nginx
  - docker push pkaranthaker/multi-server
  - docker push pkaranthaker/multi-worker
